# Configuration file for the Talea Computer System
Screen = "windowed" # "windowed", "fullscreen", or "borderless"
Dynamic_Cycles = true
CRT_shader = true
Keep_TPS_loaded = true
Sync_TPS_when_ejected = true
Key_Repeat = true
Enable_Serial = false
V-Sync = true
HiDPI = true
Port = 1212
Speed = 0.200000
Firmware = "resources/emulated/firmware/hello.bin"
TPS_A = "resources/tps_images/akai.tps"
Hardware_font = "spleen8x16.fnt"
